### ISSUE TITLE
Código de Condulta

### ISSUE THREAD

**Issue by matholiveira91** [WebDevRN/WebDevRN.github.io#4]
1. Não é admitido plágio

2. NÃO é admitido nenhum tipo de descriminação

3. Você é responsável pelo conteúdo que compartilha,bem como por qualquer consequência que isso gere 

4. Quando na lista de discussão no telegram for repreendido se retrate ou esclareça a situação o silencio pode gerar banimento do grupo

6. Respeitamos profundamente a privacidade de nossos membros,portanto não admitimos: click baits,phishsings entre outras ditas pragas da má conduta virtual, se temos regras Você deve segui-las não concorda exponha o por que com algum membro da coordenação.

7. Nosso bot tem um limite de um warn por usuário o segundo warn é ban

**Comment by igorasantos** [comment]
[This _Code of Conduct_](https://github.com/brazil-it-groups/code-of-conduct) may be usefull.

**Comment by matholiveira91** [comment]
We adopted CoC International
